### ISSUE TITLE
How to set an alarm every two days?

### ISSUE THREAD

**Issue by anrada73** [JChristensen/DS3232RTC#100]
Nice library, thanks. How is it possible to easily turn on the alarm at a given time in 1 or 2 days?

**Comment by JChristensen** [comment]
The technique would be the same as the example sketch [alarm_ex3](https://github.com/JChristensen/DS3232RTC/blob/master/examples/alarm_ex3/alarm_ex3.ino), except when [setting the alarm](https://github.com/JChristensen/DS3232RTC/blob/ef57d34517dec83029288e771add6004b46fba04/examples/alarm_ex3/alarm_ex3.ino#L54), use ALM1_MATCH_DATE instead of ALM1_MATCH_HOURS.

**Comment by anrada73** [comment]
You mean ALARM_INTERVAL ?  If in a day, then set to 86.400 seconds?

**Comment by JChristensen** [comment]
I mean:
```c++
myRTC.setAlarm(DS3232RTC::ALM1_MATCH_DATE, second, minute, hour, date);
```
